name: Check pull request

on:
  pull_request:
    branches:
      - "release/*"

jobs:
  check_version_valid_and_new:
    name: Check that the new version number is valid
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check Version
        uses: cpdevtools/action-versions@latest
        with:
          failInvalidCanCreate: true

  check_project_builds:
    name: Check that the project builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node & Dependencies
        uses: cpdevtools/common-github-workflows/.github/actions/node-setup-pnpm@v0.0.15

      - name: Build Project
        uses: cpdevtools/common-github-workflows/.github/actions/run-build@v0.0.15
